name: Publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: src/HierarchicalPropertyDefault/bin/Release/netstandard2.0/*
    - uses: actions/upload-artifact@v2
      with:
        name: HierarchicalPropertyDefault.nupkg
        path: src/HierarchicalPropertyDefault/bin/Release/HierarchicalPropertyDefault.*.nupkg
    - uses: actions/upload-artifact@v2
      with:
        name: HierarchicalPropertyDefault.snupkg
        path: src/HierarchicalPropertyDefault/bin/Release/HierarchicalPropertyDefault.*.snupkg
    - name: Publish Nuget Packages
      run: dotnet nuget push src/HierarchicalPropertyDefault/bin/Release/HierarchicalPropertyDefault.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
